### ISSUE TITLE
1.20.1 Too Fast Mixin crash

### ISSUE THREAD

**Issue by gamerpotion** [noobanidus/toofast#8]
Hey Noobanidus :)

Please see below as discussed. Crash and Mod list below it.
Carpet mod was removed prior to installing Too Fast.

```12:16:58.862
FabricLoader/Mixin
main
Mixin apply for mod toofast failed toofast.mixins.json:ServerPlayNetPlayMixin from mod toofast -> net.minecraft.class_3244: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @ModifyConstant annotation on toofast_PlayerMaxSpeed could not find any targets matching 'Lnet/minecraft/class_3244;onPlayerMove(Lnet/minecraft/class_2828;)V' in net.minecraft.class_3244. Using refmap toofast-fabric-1.20-refmap.json [PREINJECT Applicator Phase -> toofast.mixins.json:ServerPlayNetPlayMixin from mod toofast -> Prepare Injections ->  -> constant$fkh000$toofast$PlayerMaxSpeed(F)F -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyConstant annotation on toofast_PlayerMaxSpeed could not find any targets matching 'Lnet/minecraft/class_3244;onPlayerMove(Lnet/minecraft/class_2828;)V' in net.minecraft.class_3244. Using refmap toofast-fabric-1.20-refmap.json [PREINJECT Applicator Phase -> toofast.mixins.json:ServerPlayNetPlayMixin from mod toofast -> Prepare Injections ->  -> constant$fkh000$toofast$PlayerMaxSpeed(F)F -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.ModifyConstantInjectionInfo.<init>(ModifyConstantInjectionInfo.java:54)
	at jdk.internal.reflect.GeneratedConstructorAccessor68.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_8162.<clinit>(class_8162.java:33)
	at net.minecraft.class_1802.<clinit>(class_1802.java:1285)
	at net.minecraft.class_6089.method_9530(class_6089.java:56)
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1032)
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1028)
	at net.minecraft.class_4970.method_9549(class_4970.java:349)
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1293)
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:843)
	at net.minecraft.class_2246.<clinit>(class_2246.java:1185)
	at net.minecraft.class_2358.method_10199(class_2358.java:326)
	at net.minecraft.class_2966.method_12851(class_2966.java:54)
	at net.minecraft.client.main.Main.main(Main.java:166)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
12:16:58.953
FabricLoader
main
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_1802.<clinit>(class_1802.java:1285)
	at net.minecraft.class_6089.method_9530(class_6089.java:56)
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1032)
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1028)
	at net.minecraft.class_4970.method_9549(class_4970.java:349)
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1293)
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:843)
	at net.minecraft.class_2246.<clinit>(class_2246.java:1185)
	at net.minecraft.class_2358.method_10199(class_2358.java:326)
	at net.minecraft.class_2966.method_12851(class_2966.java:54)
	at net.minecraft.client.main.Main.main(Main.java:166)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3244 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_8162.<clinit>(class_8162.java:33)
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 19 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [toofast.mixins.json:ServerPlayNetPlayMixin from mod toofast] from phase [DEFAULT] in config [toofast.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 22 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyConstant annotation on toofast_PlayerMaxSpeed could not find any targets matching 'Lnet/minecraft/class_3244;onPlayerMove(Lnet/minecraft/class_2828;)V' in net.minecraft.class_3244. Using refmap toofast-fabric-1.20-refmap.json [PREINJECT Applicator Phase -> toofast.mixins.json:ServerPlayNetPlayMixin from mod toofast -> Prepare Injections ->  -> constant$fkh000$toofast$PlayerMaxSpeed(F)F -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.ModifyConstantInjectionInfo.<init>(ModifyConstantInjectionInfo.java:54)
	at jdk.internal.reflect.GeneratedConstructorAccessor68.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 22 more
12:16:59.133
launcher
main

12:16:59.133
monitor
Process Monitor
Process crashed with exit code 1
```

### Mods Installed:-
Additional Structures (Fabric/Quilt) (by XxRexRaptorxX)
Advanced Netherite (Fabric) (by AutovwDev)
Aimz - Better Crosshair (by GamerPotion)
Aimz - PVP Crosshair (by GamerPotion)
Aimz - Sniper Crosshair (by GamerPotion)
Air Chidori Origin - Origins Addon (by GamerPotion)
All The Trims (by bawnorton)
Alloy Forgery (by gliscowo)
Alternate Current (by SpaceWalkerRS)
Alternate Origin GUI (by UltrusBot)
Amethyst Core (by fzzyhmstrs)
Amethyst Imbuement (by fzzyhmstrs)
AppleSkin (by squeek502)
Architectury API (Fabric/Forge) (by shedaniel)
Azure Paxels (by AzureDoomC)
AzureLib (by AzureDoomC)
Bad Wither No Cookie - Reloaded (by Kreezxil)
Beautify: Refabricated (by Suel_ki)
Better Combat [Fabric & Forge] (by daedelus_dev)
Better Third Person (by Socolio)
Better Trims (by bawnorton)
Biome Makeover (by Lemonszz)
Cardinal Components (by UpcraftLP)
Catalogue (Fabric) (by MrCrayfish)
ChoiceTheorem's Overhauled Village (by ChoiceTheorem)
Chunky (Fabric) (by pop4959)
Cloth Config API (Fabric/Forge) (by shedaniel)
Clumps (by Jaredlll08)
Clutter (by Emil_SG)
Collective (by Serilum)
Colorful Hearts (by Terrails)
Connectivity[Forge/Fabric] (by someaddon)
Controllable (Fabric) (by MrCrayfish)
Controlling (by Jaredlll08)
Cosmetica (by eyezah)
CraftPresence (by CDAGaming_)
CraterLib (by hypherionsa)
Croptopia (by thethonk)
Crystals Overhauled [Forge & Fabric] (by superscratch4)
Dark Waters (by AzureDoomC)
DarkBindings - 100+ Recipes to Craft (by GamerPotion)
DarkCap - Cap Your XP! (by GamerPotion)
DarkFeather - Golden Feather (by GamerPotion)
DarkFlight - Simple Jetpack (by GamerPotion)
DarkHeads - Player Heads (by GamerPotion)
DarkInventory - Keep Inventory On (by GamerPotion)
DarkLoot - Better Mob Loot (by GamerPotion)
DarkMenu - DarkRPG Menu (RPG Theme) (by GamerPotion)
DarkMining - Better Block Drops (by GamerPotion)
DarkMobs - Increase Mob Difficulty (Dark Souls Like Mobs) (by GamerPotion)
DarkQuesting - Custom Quests (by GamerPotion)
DarkRewards - Item Rewards (by GamerPotion)
DarkRTP - RTP Random Teleport (by GamerPotion)
DarkSmithing - Smithing Template Recipes (for Trims) (by GamerPotion)
DarkSpawn - Teleport to Spawn or Lobby (by GamerPotion)
DarkSpins - XP Casino (by GamerPotion)
DarkStarter - Starter Items (Login Rewards) (by GamerPotion)
DarkTides - Breathe Underwater (by GamerPotion)
DarkTimer - Clear Entity Lag (by GamerPotion)
DarkWooly - Get More Wool (by GamerPotion)
Diamond Auction House (by IAmTheSneak)
Diamond Economy (by IAmTheSneak)
Dig's DnD Origins (by distantdig)
Dungeons and Taverns (by Nova_Wostra)
Durability Tooltip (by SuperMartijn642)
Durability101 Forge/Fabric 1.12-1.20 (by シェイン)
Elytra Trims (by KikuGie)
Elytra Trims Extensions (by KikuGie)
EMI (by EmilyPloszaj)
Emotecraft (Fabric) (by KosmX)
Enchanted ToolTips (by Kyrptonaught)
Extra Origins (by MoriyaShiine)
Extra Thicc Packets (by JaselUmena)
Fabric API (by modmuss50)
Fabric Language Kotlin (by modmuss50)
Fabric Waystones (by LordDeatHunter)
Farsight [Fabric] (by someaddon)
FerriteCore (Fabric) (by malte0811)
Force Crawl (by FamroFexl)
Forge Config API Port [Fabric] (by Fuzs)
Framework (Fabric) (by MrCrayfish)
Friends&Foes - Beekeeper Hut (Fabric) (by faboslav)
Friends&Foes - Flowery Mooblooms (Fabric) (by faboslav)
Friends&Foes (Fabric) (by faboslav)
Fzzy Core (by fzzyhmstrs)
GeckoLib (by Gecko)
Geode+ [Forge/Fabric] (by YeoXuHang)
Geophilic – Biome Overhauls (by bebebea_loste)
Get It Together, Drops! (by bl4ckscor3)
Global Packs (by JTK222)
Golden Berries (by AzureDoomC)
Gothic RPG Font (by GamerPotion)
Grind Enchantments (by mschae23)
Handcrafted (by kekie6)
Harvest Scythes (by LordDeatHunter)
Healing Campfire (by Serilum)
Held Item Info (by Neecko5b84)
ImmediatelyFast (by RaphiMC)
Immersive Aircraft [Fabric/Forge] (by Conczin)
Inventory HUD+ (by dmitrylovin)
Inventory Sorting (by Kyrptonaught)
Item Obliterator [Fabric/Quilt] (by ElocinDev)
Jade 🔍 (by Snownee_)
JamLib (by jamalam360)
LazyDFU (by tuxed)
LibreExpFix (Fixes "0 Experience" Bug) (by ZiRO2264)
Limited Spawners (Fabric) (by StrikerRocker)
Link's Font (by GamerPotion)
Loading Screen Tips (by UltrusBot)
Log Begone (by AzureDoomC)
Login Protection[Forge/Fabric] (by someaddon)
Lootr (Fabric) (by Noobanidus)
Macaw's Bridges (by sketch_macaw)
Macaw's Fences and Walls (by sketch_macaw)
Macaw's Lights and Lamps (by sketch_macaw)
Macaw's Paths and Pavings (by sketch_macaw)
Macaw's Roofs (by sketch_macaw)
Macaw's Trapdoors (by sketch_macaw)
MaLiLib (by masady)
Marium's Soulslike Weaponry (by mariumbacchus)
Melius Vanish (by drexhd)
Menulogue (by MrCrayfish)
Midas Hunger [Fabric\|Quilt\|Forge] (by Accieo)
MiniHUD (by masady)
More Armor Trims [FABRIC] (by masik16u)
More Bows: Restrung! (by NeRdTheNed)
Mouse Tweaks (by YaLTeR)
Mythic Metals (by Noaaan)
Mythic Upgrades [FABRIC] (by trique06)
Neruina - Ticking Entity Fixer (by bawnorton)
No Chat Reports (by Aizistral)
No Hostiles Around Campfire (by Serilum)
No See, No Tick (by Vishnu)
Nyctophobia (FABRIC) (by finallion_13)
Open Parties and Claims (by xaero96)
Origins (Fabric) (by Apace)
Origins: Classes (by Apace)
oωo (owo-lib) (by gliscowo)
Pehkui (by Virtuoel)
playerAnimator (by KosmX)
Plenty Of Armors [Fabric] (by aleganza)
Plushie Mod (by Link4real)
Polymorph (Fabric/Forge/Quilt) (by TheIllusiveC4)
Pufferfish's Skills [Forge & Fabric] (by Pufferfish)
Pumpkillager's Quest (by Serilum)
Regions Unexplored (forge/fabric) (by UHQ_GAMES)
Reinforced Barrels (by atonkish)
Reinforced Chests (by atonkish)
Reinforced Shulker Boxes (by atonkish)
Resourceful Lib (by ThatGravyBoat)
RPG Origins (by Sir_BananaCat)
RPG PVP Swords and Tools (by GamerPotion)
Searchables (by Jaredlll08)
Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)
ServerCore (by Wesley8081)
Show Me Your Skin! (Hide armor) (by enjarai)
Simple Discord Link Bot [Forge/Fabric] (by hypherionsa)
Simply Houses (by Aureljz)
Simply Swords [Fabric & Forge] (by sweenuss)
Sky Villages [Fabric] (by Aureljz)
SmartBrainLib (Forge/Fabric/Quilt) (by Scimiguy)
Sodium (by jellysquid3_)
spark (by Iucko)
Starlight (Fabric) (by Spottedstar)
Structure Essentials[Forge/Fabric] (by someaddon)
Super RPG Font (by GamerPotion)
SuperMartijn642's Config Lib (by SuperMartijn642)
Tech RPG Font (by GamerPotion)
TerraBlender (Fabric) (by TheAdubbz)
The Graveyard (FABRIC) (by finallion_13)
Things [Fabric] (by gliscowo)
Tiny PVP Swords and Tools (by GamerPotion)
Tom's Trading Network (by tom54541)
Too Fast (by Noobanidus)
ToolTipFix (by Kyrptonaught)
Trade Cycling (by henkelmax)
TrimsEffects (by lupiiin_)
Trinkets (Fabric) (by EmilyPloszaj)
U Team Core (by HyCraftHD)
Useful Backpacks (by HyCraftHD)
Utility Belt (by jamalam360)
Wall Jumped (by AzureDoomC)
When Dungeons Arise - Fabric! (by Aureljz)
WI Zoom (by alexander9892)
WorldEdit (by sk89q)
Xaero's Minimap (by xaero96)
Xaero's World Map (by xaero96)
Zen Font (by GamerPotion)

**Comment by noobanidus** [comment]
Ah, I see that it appears to be unable to find the actual mixin injection target, rather than conflicting with another mod. I'll dig into it deeper. Is this 1.20.1 or 1.20.0? Ah, I see 1.20.1.

**Comment by noobanidus** [comment]
Looks like the refmap isn't being created properly. I'll look into it.

**Comment by noobanidus** [comment]
Ah, I forgot to update Loom. 1.2.0 should fix this, I'm uploading it now.
